openapi: 3.0.0
info:
  version: "0.0.1"
  title: "Semantic Mediator"
servers:
  - url: http://localhost:8000

paths:
  /mediation:
    get:
      description: "Return list of current available mediations"
      operationId: getMediationList
      tags:
        - Mediation
      security:
        - bearerAuth: []
      responses:
        "200":
          $ref: "#/components/responses/MediationListResponse"
    post:
      description: "Return list of current available mediations"
      operationId: addMediation
      tags:
        - Mediation
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/addMediationRequest"
      responses:
        "200":
          $ref: "#/components/responses/MediationListResponse"
  /mediation/{id}:
    get:
      description: "Return mediation of given id"
      operationId: getMediation
      tags:
        - Mediation
      security:
        - bearerAuth: []
      summary: Get mediation by ID
      parameters:
        - name: id
          in: path
          description: ID of the mediation
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          $ref: "#/components/responses/MediationResponse"
  /mediate:
    post:
      description: "Mediate according to the body request"
      operationId: mediate
      tags:
        - Mediate
      security:
        - bearerAuth: []
      summary: Mediate
      requestBody:
        $ref: "#/components/requestBodies/mediateRequest"
      response:
        "200":
          $ref: "#/components/responses/mediateResponse/content"
        "400":
          description: "Invalid request"
components:
  requestBodies:
    addMediationRequest:
      description: "Add mediation request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Mediation"
    mediateRequest:
      description: "Mediate, do the mediation."
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                example: "Convert Celcius to Kelvins"
              inputValue:
                type: number
                example: "45"
              unit:
                type: string
                example: "C"
  responses:
    MediationListResponse:
      description: "Return list of the all mediations"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MediationList"
    MediationResponse:
      description: "Return mediation"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Mediation"
    mediateResponse:
      description: "Mediation response."
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                example: "Convert Celcius to Kelvins"
              outputValue:
                type: number
                example: "318.15"
              unit:
                type: string
                example: "K"
  schemas:
    Metadata:
      properties:
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
          example: "admin@accordion.eu"
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string
          example: "user@accordion.eu"
    NewMediation:
      type: object
      properties:
        name:
          type: string
          example: "Kelvin-Celsius"
        content:
          type: object
    Mediation:
      allOf:
        - $ref: "#/components/schemas/NewMediation"
        - type: object
          properties:
            id:
              type: string
              format: uuid
            metadata:
              $ref: "#/components/schemas/Metadata"
    MediationList:
      type: array
      items:
        $ref: "#/components/schemas/Mediation"

  securitySchemes:
    bearerAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://CEIoTProject.eu/oauth/authorize
          tokenUrl: https://CEIoTProject.eu/oauth/token
          scopes:
            read: Read access
            write: Write access
